import { User } from "@/app/users/columns";

export async function getUserData(): Promise<User[]> {
  return [
    {
      id: "728ed521",
      username: "John Doe",
      email: "johndoe@gmail.com",
      status: "active",
      balance: 289,
    },
    {
      id: "728ed522",
      username: "Jane Doe",
      email: "janedoe@gmail.com",
      status: "active",
      balance: 412,
    },
    {
      id: "728ed523",
      username: "Mike Galloway",
      email: "mikegalloway@gmail.com",
      status: "inactive",
      balance: 167,
    },
    {
      id: "728ed524",
      username: "Minerva Robinson",
      email: "minerbarobinson@gmail.com",
      status: "active",
      balance: 523,
    },
    {
      id: "728ed525",
      username: "Mable Clayton",
      email: "mableclayton@gmail.com",
      status: "inactive",
      balance: 145,
    },
    {
      id: "728ed526",
      username: "Nathan McDaniel",
      email: "nathanmcdaniel@gmail.com",
      status: "active",
      balance: 378,
    },
    {
      id: "728ed527",
      username: "Myrtie Lamb",
      email: "myrtielamb@gmail.com",
      status: "active",
      balance: 256,
    },
    {
      id: "728ed528",
      username: "Leona Bryant",
      email: "leonabryant@gmail.com",
      status: "suspended",
      balance: 190,
    },
    {
      id: "728ed529",
      username: "Aaron Willis",
      email: "aaronwillis@gmail.com",
      status: "inactive",
      balance: 98,
    },
    {
      id: "728ed52a",
      username: "Joel Keller",
      email: "joelkeller@gmail.com",
      status: "active",
      balance: 543,
    },
    {
      id: "728ed52b",
      username: "Daniel Ellis",
      email: "danielellis@gmail.com",
      status: "active",
      balance: 312,
    },
    {
      id: "728ed52c",
      username: "Gordon Kennedy",
      email: "gordonkennedy@gmail.com",
      status: "inactive",
      balance: 345,
    },
    {
      id: "728ed52d",
      username: "Emily Hoffman",
      email: "emilyhoffman@gmail.com",
      status: "active",
      balance: 419,
    },
    {
      id: "728ed52e",
      username: "Jeffery Garrett",
      email: "jefferygarrett@gmail.com",
      status: "suspended",
      balance: 664,
    },
    {
      id: "728ed52f",
      username: "Ralph Baker",
      email: "ralphbaker@gmail.com",
      status: "inactive",
      balance: 332,
    },
    {
      id: "728ed52g",
      username: "Seth Fields",
      email: "sethfields@gmail.com",
      status: "active",
      balance: 413,
    },
    {
      id: "728ed52h",
      username: "Julia Webb",
      email: "juliawebb@gmail.com",
      status: "active",
      balance: 298,
    },
    {
      id: "728ed52i",
      username: "Gary Banks",
      email: "garybanks@gmail.com",
      status: "inactive",
      balance: 487,
    },
    {
      id: "728ed52j",
      username: "Flora Chambers",
      email: "florachambers@gmail.com",
      status: "active",
      balance: 643,
    },
    {
      id: "728ed52k",
      username: "Steve Hanson",
      email: "stevehanson@gmail.com",
      status: "suspended",
      balance: 543,
    },
    {
      id: "728ed52l",
      username: "Lola Robinson",
      email: "lolarobinson@gmail.com",
      status: "inactive",
      balance: 324,
    },
    {
      id: "728ed52m",
      username: "Ethel Waters",
      email: "ethelwaters@gmail.com",
      status: "active",
      balance: 187,
    },
    {
      id: "728ed52n",
      username: "Grace Edwards",
      email: "graceedwards@gmail.com",
      status: "active",
      balance: 422,
    },
    {
      id: "728ed52o",
      username: "Sallie Wong",
      email: "salliewong@gmail.com",
      status: "inactive",
      balance: 512,
    },
    {
      id: "728ed52p",
      username: "Bryan Gutierrez",
      email: "bryangutierrez@gmail.com",
      status: "active",
      balance: 360,
    },
    {
      id: "728ed52q",
      username: "Erik Rice",
      email: "erikrice@gmail.com",
      status: "suspended",
      balance: 454,
    },
    {
      id: "728ed52r",
      username: "Jordan Atkins",
      email: "jordanatkins@gmail.com",
      status: "inactive",
      balance: 382,
    },
    {
      id: "728ed52s",
      username: "Bill Brewer",
      email: "billbrewer@gmail.com",
      status: "active",
      balance: 328,
    },
    {
      id: "728ed52t",
      username: "Edwin Morris",
      email: "edwinmorris@gmail.com",
      status: "active",
      balance: 250,
    },
    {
      id: "728ed52u",
      username: "Harold Becker",
      email: "haroldbecker@gmail.com",
      status: "inactive",
      balance: 658,
    },
    {
      id: "728ed52v",
      username: "Hannah Rodriguez",
      email: "hannahrodriguez@gmail.com",
      status: "active",
      balance: 691,
    },
    {
      id: "728ed52w",
      username: "Zachary Beck",
      email: "zacharybeck@gmail.com",
      status: "suspended",
      balance: 969,
    },
    {
      id: "728ed52x",
      username: "Frances Potter",
      email: "francespotter@gmail.com",
      status: "inactive",
      balance: 617,
    },
    {
      id: "728ed52y",
      username: "Raymond Murray",
      email: "raymondmurray@gmail.com",
      status: "active",
      balance: 173,
    },
    {
      id: "728ed52z",
      username: "Adam Sherman",
      email: "adamsherman@gmail.com",
      status: "active",
      balance: 721,
    },
    {
      id: "728ed521f",
      username: "Anne Cruz",
      email: "annecruz@gmail.com",
      status: "inactive",
      balance: 914,
    },
  ];
}
